
package com.amplifino.nestor.soap.sample;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SampleWebServiceService", targetNamespace = "http://sample.soap.nestor.amplifino.com/", wsdlLocation = "http://localhost:8080/soap/sample?WSDL")
public class SampleWebServiceService
    extends Service
{

    private final static URL SAMPLEWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SAMPLEWEBSERVICESERVICE_EXCEPTION;
    private final static QName SAMPLEWEBSERVICESERVICE_QNAME = new QName("http://sample.soap.nestor.amplifino.com/", "SampleWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap/sample?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAMPLEWEBSERVICESERVICE_WSDL_LOCATION = url;
        SAMPLEWEBSERVICESERVICE_EXCEPTION = e;
    }

    public SampleWebServiceService() {
        super(__getWsdlLocation(), SAMPLEWEBSERVICESERVICE_QNAME);
    }

    public SampleWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAMPLEWEBSERVICESERVICE_QNAME, features);
    }

    public SampleWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SAMPLEWEBSERVICESERVICE_QNAME);
    }

    public SampleWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAMPLEWEBSERVICESERVICE_QNAME, features);
    }

    public SampleWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SampleWebService
     */
    @WebEndpoint(name = "SampleWebServicePort")
    public SampleWebService getSampleWebServicePort() {
        return super.getPort(new QName("http://sample.soap.nestor.amplifino.com/", "SampleWebServicePort"), SampleWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SampleWebService
     */
    @WebEndpoint(name = "SampleWebServicePort")
    public SampleWebService getSampleWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sample.soap.nestor.amplifino.com/", "SampleWebServicePort"), SampleWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAMPLEWEBSERVICESERVICE_EXCEPTION!= null) {
            throw SAMPLEWEBSERVICESERVICE_EXCEPTION;
        }
        return SAMPLEWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
