
package com.amplifino.nestor.soap.sample;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SampleWebService", targetNamespace = "http://sample.soap.nestor.amplifino.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SampleWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://sample.soap.nestor.amplifino.com/", className = "com.amplifino.nestor.soap.sample.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://sample.soap.nestor.amplifino.com/", className = "com.amplifino.nestor.soap.sample.AddResponse")
    @Action(input = "http://sample.soap.nestor.amplifino.com/SampleWebService/addRequest", output = "http://sample.soap.nestor.amplifino.com/SampleWebService/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
