package com.amplifino.nestor.soap.test;

import org.junit.Assert;
import org.junit.Test;

import com.amplifino.nestor.soap.sample.SampleWebService;
import com.amplifino.nestor.soap.sample.SampleWebServiceService;

/**
 * SampleWebService classes in package com.amplifino.nestor.soap.sample were generated by the wsimport jdk tool.
 * wsimport -keep http://localhost:8080/soap/sample?WSDL.
 * 
 *
 */
public class SoapTest {

	@Test
	public void test() throws InterruptedException {
		Thread.sleep(1000L);
		SampleWebServiceService service = new SampleWebServiceService();
		SampleWebService port = service.getSampleWebServicePort();
		Assert.assertEquals(2, port.add(1, 1));
	}
}
